"""
sandbox_runner.py — Docker-based Python code execution sandbox.

Runs agent-generated code in an isolated throwaway container with:
- No network access
- No filesystem access outside /tmp
- CPU + memory hard limits
- 30-second execution timeout
- Container destroyed immediately after execution

Flow:
    validate_code() → run_in_sandbox() → parse output → return result
"""

import logging
import time
import tempfile
import os
import docker
from docker.errors import DockerException, ContainerError, ImageNotFound

from backend.engines.sandbox.code_validator import validate_code
from backend.engines.sandbox.result_formatter import format_result

logger = logging.getLogger(__name__)

# ─── Configuration ────────────────────────────────────────────────────────────

SANDBOX_IMAGE = "jupyter/scipy-notebook:latest"       # Base Docker image
EXECUTION_TIMEOUT = 30                    # Seconds before container killed
MEMORY_LIMIT = "256m"                     # Max RAM per execution
CPU_QUOTA = 50000                         # 50% of one CPU core (out of 100000)
MAX_OUTPUT_CHARS = 10_000                 # Truncate output beyond this


# ─── Pre-installed packages in sandbox ───────────────────────────────────────
# These are injected as a pip install before running user code.
# Kept minimal to keep container startup fast.

SANDBOX_PACKAGES = [
    "pandas", "numpy", "scikit-learn",
    "matplotlib", "seaborn", "scipy",
]

PACKAGE_INSTALL_CMD = f"pip install -q {' '.join(SANDBOX_PACKAGES)} && "


# ─── Public API ───────────────────────────────────────────────────────────────

def run_in_sandbox(code: str) -> dict:
    """Validate and execute Python code in an isolated Docker container.

    Complete sandbox execution pipeline with security validation and resource limits.
    
    Execution Steps:
    1. Validate code (AST + RestrictedPython) — reject if unsafe
    2. Connect to Docker daemon
    3. Build shell command with package pre-installation
    4. Spin up throwaway Docker container with strict resource limits
    5. Execute code with timeout and capture output
    6. Destroy container immediately
    7. Format and return result
    
    Security Features:
    - No network access (network_disabled=True)
    - No privileged access
    - CPU quota limited to 50% of one core
    - Memory hard limit (256MB)
    - Read-only root filesystem (except /tmp)
    - 30-second execution timeout
    - Pre-execution validation (AST + RestrictedPython)
    
    Package Environment:
    - Pre-installed (injected before code): pandas, numpy, scikit-learn, 
      matplotlib, seaborn, scipy
    - Installation happens once per container (in build command)
    
    Error Handling:
    - Validation failure: Returns error dict, never touches Docker
    - Docker not running: Caught, returns helpful error message
    - Code runtime error: Captured stderr/returncode, formatted as error
    - Timeout: Detected and formatted as specific error message
    - Any exception: Caught, formatted, never raises to caller
    
    Args:
        code (str):
            Python source code generated by the agent.
            - Type: String of valid Python code
            - Validation: Checked by validate_code() before Docker invocation
            - Example: 'import pandas as pd; data = pd.read_csv(...); print(data.head())'
            - Execution context: Clean Python environment with allowed packages
            - Stdin: Not provided (code cannot accept user input)
            - Performance assumption: Code should complete in <30s

    Returns:
        dict: Complete sandbox execution result with keys:
        
        success (bool):
            True if code executed without errors or timeout
            - False if: validation failed, Docker error, runtime error, or timeout
            - Usage: Check first before accessing other fields
        
        output (str):
            stdout captured during execution
            - Type: String (may contain multiple lines)
            - Content: Print statements and output from code
            - Empty if: Code produced no output or execution failed
            - Max length: Truncated to MAX_OUTPUT_CHARS (10,000) to prevent overflow
            - Format: Raw text with newlines preserved
        
        error (str or None):
            Error message if execution failed
            - Type: String or None
            - None if: success=True (no error)
            - Content: Human-readable error description
            - Examples:
              - "Code validation failed: Blocked import: 'os'"
              - "Docker is not running. Please start Docker Desktop."
              - "Runtime error: ZeroDivisionError: division by zero"
              - "Execution timed out after 30s"
        
        execution_time (float):
            Wall-clock time spent in sandbox (seconds)
            - Type: Float (seconds), rounded to 2 decimal places
            - Includes: Package installation + code execution
            - Does NOT include: Validation time or Docker overhead
            - Typical range: 5-30 seconds depending on code
            - Metric: Used to assess performance and timeouts
        
        validation_warnings (list):
            Non-fatal security validation warnings
            - Type: List of strings
            - Format: Each warning describes a suspicious pattern (not blocked)
            - Example: "Unknown module: 'my_custom_lib'"
            - Content: Warnings from both AST visitor and RestrictedPython Check
            - Action: Allowed execution but flagged for review
    
    Performance Characteristics:
        - Validation: ~10-50ms (depends on code size)
        - Docker startup: ~1-2 seconds (container creation overhead)
        - Package installation: ~3-5 seconds (first container run)
        - Code execution: Variable (depends on code)
        - Container cleanup: <100ms
        - Total typical: 5-30 seconds per sandbox run
    
    Docker Image and Configuration:
        - Image: python:3.11-slim (lightweight Python environment)
        - Timeout: 30 seconds hard limit (docker timeout parameter)
        - Memory: 256MB hard limit (mem_limit)
        - CPU: 50% of one core (cpu_quota=50000)
        - Filesystem: Read-only root except /tmp (64MB tmpfs)
        - Network: Completely disabled
        - Removal: Auto-cleanup after execution (remove=True)
    
    Exception Safety:
        - Never raises exceptions to caller
        - All errors caught and formatted as return dict
        - Container cleanup guaranteed (even if code crashes)
        - Resource limits enforced (can't exhaust host system)
    """
    start_time = time.time()

    # ── Step 1: Validate before touching Docker ───────────────────────────────
    validation = validate_code(code)

    if not validation.is_valid:
        logger.warning(f"Code rejected by validator: {validation.errors}")
        return {
            "success": False,
            "output": "",
            "error": f"Code validation failed: {'; '.join(validation.errors)}",
            "execution_time": 0.0,
            "validation_warnings": validation.warnings,
        }

    if validation.warnings:
        logger.info(f"Validation warnings: {validation.warnings}")

    # ── Step 2: Connect to Docker ─────────────────────────────────────────────
    try:
        client = docker.from_env()
    except DockerException as e:
        logger.error(f"Docker connection failed: {e}")
        return {
            "success": False,
            "output": "",
            "error": "Docker is not running. Please start Docker Desktop.",
            "execution_time": 0.0,
            "validation_warnings": validation.warnings,
        }

    # ── Step 3: Write code to a temp file and mount it ──────────────────────
    # Avoids all quote escaping issues by mounting the code as a file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
        f.write(code)
        temp_path = f.name

    # ── Step 4: Run container ─────────────────────────────────────────────────
    try:
        try:
            logger.info("Starting sandbox container...")

            container = client.containers.create(
                image=SANDBOX_IMAGE,
                command=["python", "/tmp/code.py"],
                network_disabled=True,
                mem_limit=MEMORY_LIMIT,
                cpu_quota=CPU_QUOTA,
                read_only=True,
                tmpfs={"/tmp": "size=64m"},
                volumes={temp_path: {"bind": "/tmp/code.py", "mode": "ro"}},
                environment={"MPLCONFIGDIR": "/tmp/matplotlib"},
            )

            try:
                container.start()
                exit_status = container.wait(timeout=EXECUTION_TIMEOUT)
                raw_output = container.logs(stdout=True, stderr=True).decode("utf-8", errors="replace")
                
                if exit_status["StatusCode"] != 0:
                    raise ContainerError(
                        container, exit_status["StatusCode"],
                        "python /tmp/code.py", SANDBOX_IMAGE, raw_output.encode()
                    )
            finally:
                container.remove(force=True)  # Always destroy, even on error

            execution_time = time.time() - start_time
            raw_output = raw_output

            # Truncate if too long
            if len(raw_output) > MAX_OUTPUT_CHARS:
                raw_output = raw_output[:MAX_OUTPUT_CHARS] + "\n[output truncated]"

            logger.info(f"Sandbox execution completed in {execution_time:.2f}s")

            return {
                "success": True,
                "output": raw_output.strip(),
                "error": None,
                "execution_time": round(execution_time, 2),
                "validation_warnings": validation.warnings,
            }

        except ContainerError as e:
            # Code ran but exited with non-zero status (runtime error)
            execution_time = time.time() - start_time
            stderr = e.stderr.decode("utf-8", errors="replace") if e.stderr else str(e)
            logger.warning(f"Container runtime error: {stderr[:200]}")
            return {
                "success": False,
                "output": "",
                "error": f"Runtime error: {stderr[:500]}",
                "execution_time": round(execution_time, 2),
                "validation_warnings": validation.warnings,
            }

        except Exception as e:
            execution_time = time.time() - start_time
            error_msg = str(e)

            # Detect timeout specifically
            if "timeout" in error_msg.lower() or "timed out" in error_msg.lower():
                logger.warning("Sandbox execution timed out")
                return {
                    "success": False,
                    "output": "",
                    "error": f"Execution timed out after {EXECUTION_TIMEOUT}s",
                    "execution_time": round(execution_time, 2),
                    "validation_warnings": validation.warnings,
                }

            logger.error(f"Sandbox unexpected error: {e}")
            return {
                "success": False,
                "output": "",
                "error": f"Sandbox error: {error_msg}",
                "execution_time": round(execution_time, 2),
                "validation_warnings": validation.warnings,
            }
    finally:
        os.unlink(temp_path)  # Always clean up temp file